edit des projet ds un modal
RignonNoel/ionic-tasklist pull request #28
Opened 2017-03-29 14:59 UTC by Jonathan92ETS

| Question               | Answer
| ---------------------- | -
| Bugs correction ?      | yes/no
| New features ?         | yes/no
| Related issues         | #number

---

##### What have you changed  ?
...

##### How did you do that ?
...

2017-03-29 15:21 UTC, RignonNoel requested changes
Hi! Thx for this PR! 👍 

It seems that you are not using the same architecture as the one used for tasks edition. That would be surely a good point.

Anyway it seems work but there are some little details to be consistent.

2017-03-29 15:21 UTC, RignonNoel commented on tasklist/src/config/env.json
> +	"environment": "production"
please let the development mode by default in the repository

2017-03-29 15:21 UTC, RignonNoel commented on tasklist/src/pages/listProject/listProject.html
> +          Edit
Please use the same icon as the task edition to keep a good user experience.

2017-03-29 18:06 UTC, Jonathan92ETS commented
- Ajout de la possibilité de modifié le projet a partir du menu de Task List
- Modification de l'icon
- Environment a development

2017-03-29 19:20 UTC, RignonNoel requested changes
Please check the PR #25 to edit task made by @kristofbc . His architecture ust need to be copy/paste to project

2017-03-29 19:20 UTC, RignonNoel commented on tasklist/src/pages/listProject/listProject.html
> +          Edit
Please check the edit button of task made by @kristofbc.
```
<ion-buttons end>
  <button ion-button icon-only (click)="editTapped($event)">
    <ion-icon name="brush"></ion-icon>
  </button>
</ion-buttons>
```

2017-03-29 19:25 UTC, Jonathan92ETS commented on tasklist/src/pages/listProject/listProject.html
> +          Edit
C'est deja copié... 
J'ai juste laisser l'autre aussi, mais je peut le supprimer si tu veut juste un point d entrer pour la modif

2017-03-30 01:29 UTC, RignonNoel commented
I don't know if you see my general comment on the review so i just want to copy/paste here to you.

The PR work but you don't have the correct architecture to be consistent with the PR of Kristof, the PR #25 is an exemple of his works. A simple copy paste of some attribute seems be ok to redo this PR on project.

---
**1st review**

Hi! Thx for this PR! 👍
It seems that you are not using the same architecture as the one used for tasks edition. That would be surely a good point.
Anyway it seems work but there are some little details to be consistent.

---
**2nd review**
Please check the PR #25 to edit task made by @kristofbc . His architecture just need to be copy/paste to project

2017-03-30 16:22 UTC, RignonNoel requested changes
Yeah, seems good to me. 

You just rename your commit to fit with the max char length and we're in business ;)

2017-03-30 21:38 UTC, RignonNoel approved these changes

2017-03-30 21:38 UTC, RignonNoel commented
I let you the pleasure to merge with the big green button ;)

2017-03-30 21:39 UTC, merged